### PR TITLE
Clean makefiles, add installation instructions, fix readHap

### PR DESCRIPTION
**Pull request by johnlees**
Remove the icc makefile: it’s not very general and the gcc option gives
similar performance
Update the makefile: compiler into variable. Add -O3 flag which roughly
trebles execution speed
Add brief installation instructions to readme

### CODE REVIEW

**Comment by johnlees** [comment]
I've also fixed a bug in -readHap: .hap files were being treated the same as .gen files which have 5 columns of site information at the start so were being incorrectly parsed. This would also error on reaching the end of the line as an odd number of fields would be found.

I don't like the fix: it duplicates code. Maybe you could think of a more elegant way of doing it, but maybe it'll do for now
It's worth having the feature I reckon, as this is the default format of any pre-phased data from shapeit2 (I've done this because someone was trying to use it and having trouble)

**Comment by richarddurbin** [comment]
I am happy with the makefile change, but can't fully understand the HapLegend stuff.  I'll look again when I have more time (flight about to take off).  A minor thing, but shouldn't the string in
PBWT *pbwtReadHap (FILE *fp, char *chrom) be "hap" not "hap-legend" which you changed it to?

- PBWT *p = pbwtReadLineFile (fp, "hap", parseHapLine) ; 	
+ PBWT *p = pbwtReadLineFile (fp, "hap-legend", parseHapLine) ;

**Comment by johnlees** [comment]
I've fixed that type in the string in commit 449d9d5 now

readHapLegend is a bit of a workaround as we need to read two files simultaneously, which as far as I can tell is done yet anywhere else in the code. I've introduced the new file pointer *lp to read the legend file, while using *fp to read the hap file. I've ended up duplicating a function adding an extra argument as I don't know of a way to have an optional argument in C.

An introduction of a define for the preprocessor mirroring FOPEN for fp is introducted: LOPEN. Might be better to allow this define to be passed the file pointer?

Perhaps it would be better to use just one function accepting two file pointer arguments, always passing lp but only using it for readHapLegend? I think that would avoid duplicating code.

If that seems better I can try making that change this week

**Comment by johnlees** [comment]
Also now fixes a bug in referenceImpute when imputing a large number of samples into a small reference panel

**Pull request merged**
